# This file was generated by https://github.com/kamilchm/go2nix v1.2.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "oauth2_proxy-${version}";
  version = "2.2";
  rev = "b90a23473f10c7bb2d84acd033f7d7ed81b95dd3";

  goPackagePath = "github.com/bitly/oauth2_proxy";

  src = fetchgit {
    inherit rev;
    url = "https://github.com/bitly/oauth2_proxy";
    sha256 = "06lp2ssd4nnslr3v13rwng9mg7ih6yxf6bwd083n5za58hh11jvc";
  };

  goDeps = ./deps.nix;

  meta = {
    description = "A reverse proxy that provides authentication with Google, Github or other provider";
    homepage = "https://github.com/bitly/oauth2_proxy";
    license = stdenv.lib.licenses.mit;
  };
}
