# This file was generated by https://github.com/kamilchm/go2nix v1.2.0
[
  {
    goPackagePath = "cloud.google.com/go";
    fetch = {
      type = "git";
      url = "https://code.googlesource.com/gocloud";
      rev = "3e1507a0d90d17e4fdd8ef75e8f037ebecc854ba";
      sha256 = "1m2xd7knmwlaz26av60mmg0r37mvqfddc0r9chdb1847qbhk5p1k";
    };
  }
  {
    goPackagePath = "github.com/18F/hmacauth";
    fetch = {
      type = "git";
      url = "https://github.com/18F/hmacauth";
      rev = "9232a6386b737d7d1e5c1c6e817aa48d5d8ee7cd";
      sha256 = "056mcqrf2bv0g9gn2ixv19srk613h4sasl99w9375mpvmadb3pz1";
    };
  }
  {
    goPackagePath = "github.com/BurntSushi/toml";
    fetch = {
      type = "git";
      url = "https://github.com/BurntSushi/toml";
      rev = "a368813c5e648fee92e5f6c30e3944ff9d5e8895";
      sha256 = "1sjxs2lwc8jpln80s4rlzp7nprbcljhy5mz4rf9995gq93wqnym5";
    };
  }
  {
    goPackagePath = "github.com/bitly/go-simplejson";
    fetch = {
      type = "git";
      url = "https://github.com/bitly/go-simplejson";
      rev = "da1a8928f709389522c8023062a3739f3b4af419";
      sha256 = "0r5vfhbniqys4g5fy7r4gph4vd3g0ss53gb9brw8k6yycz5kywwa";
    };
  }
  {
    goPackagePath = "github.com/mreiferson/go-options";
    fetch = {
      type = "git";
      url = "https://github.com/mreiferson/go-options";
      rev = "77551d20752b54535462404ad9d877ebdb26e53d";
      sha256 = "02c18zrx038gbas58l90xzsz9m5q3gpjprdcwmnvxsn0zvld0vpj";
    };
  }
  {
    goPackagePath = "golang.org/x/net";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/net";
      rev = "f01ecb60fe3835d80d9a0b7b2bf24b228c89260e";
      sha256 = "0j992rd9mjbyqmn53b5g41x8x0i1q8723qy8138fj96brqis3xda";
    };
  }
  {
    goPackagePath = "golang.org/x/oauth2";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/oauth2";
      rev = "cce311a261e6fcf29de72ca96827bdb0b7d9c9e6";
      sha256 = "1fc3amcm8kj7343l63n2i069hc1qsfvxdqcfzg9a8yzk9bbz9x0r";
    };
  }
  {
    goPackagePath = "golang.org/x/sys";
    fetch = {
      type = "git";
      url = "https://go.googlesource.com/sys";
      rev = "abf9c25f54453410d0c6668e519582a9e1115027";
      sha256 = "0dmpqjfif2zg6776d366js60k21g81jvsr3jm9dc7fv7w3282al4";
    };
  }
  {
    goPackagePath = "google.golang.org/api";
    fetch = {
      type = "git";
      url = "https://code.googlesource.com/google-api-go-client";
      rev = "e665075b5ff79143ba49c58fab02df9dc122afd5";
      sha256 = "0mkbi92ppdb3kf67rrvv1a7mg2kqw1mybvll2pw6irgbxjvfy9yh";
    };
  }
  {
    goPackagePath = "gopkg.in/fsnotify.v1";
    fetch = {
      type = "git";
      url = "https://gopkg.in/fsnotify.v1";
      rev = "629574ca2a5df945712d3079857300b5e4da0236";
      sha256 = "06wfg1mmzjj04z7d0q1x2fai9k6hm957brngsaf02fa9a3qqanv3";
    };
  }
]
